### ISSUE TITLE
Google Cloud Key JSON

### ISSUE THREAD

**Issue by rmscoal** [bezkoder/google-cloud-storage-nodejs-upload-file#1]
Hello, I have some question regarding the cloud storage JSON key. I am trying to learn about it.

Question is, how do I get the JSON key file. Is it a service account or something else?

Thanks in advance.

**Comment by vhinvergara** [comment]
https://www.bezkoder.com/google-cloud-storage-free/

**Comment by DevKaranMehta** [comment]
The code working well! Is there any way to track the uploading progress ? 

Thanks
